### ISSUE TITLE
0.8.0: Fails to build due to libfmt issues

### ISSUE THREAD

**Issue by yurivict** [bluescarni/obake#150]
```
===>  Building for obake-0.8.0
[ 25% 2/4] /usr/local/libexec/ccache/c++ -DFMT_SHARED -Dobake_EXPORTS -I/usr/ports/math/obake/work/obake-0.8.0/include -I/usr/ports/math/obake/work/.build/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -ftemplate-depth=1024 -fdiagnostics-show-template-tree -pthread -std=c++20 -MD -MT CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o -MF CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o.d -o CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o -c /usr/ports/math/obake/work/obake-0.8.0/src/polynomials/d_packed_monomial.cpp
FAILED: CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o 
/usr/local/libexec/ccache/c++ -DFMT_SHARED -Dobake_EXPORTS -I/usr/ports/math/obake/work/obake-0.8.0/include -I/usr/ports/math/obake/work/.build/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -ftemplate-depth=1024 -fdiagnostics-show-template-tree -pthread -std=c++20 -MD -MT CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o -MF CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o.d -o CMakeFiles/obake.dir/src/polynomials/d_packed_monomial.cpp.o -c /usr/ports/math/obake/work/obake-0.8.0/src/polynomials/d_packed_monomial.cpp
In file included from /usr/ports/math/obake/work/obake-0.8.0/src/polynomials/d_packed_monomial.cpp:16:
In file included from /usr/ports/math/obake/work/obake-0.8.0/include/obake/polynomials/d_packed_monomial.hpp:30:
/usr/local/include/fmt/core.h:2743:12: error: call to deleted constructor of 'conditional_t<has_formatter<mapped_type, context>::value, formatter<mapped_type, char_type>, fallback_formatter<stripped_type, char_type>>' (aka 'fmt::detail::fallback_formatter<mppp::integer<1>>')
  auto f = conditional_t<has_formatter<mapped_type, context>::value,
           ^
/usr/local/include/fmt/core.h:2954:23: note: in instantiation of function template specialization 'fmt::detail::parse_format_specs<mppp::integer<1>, fmt::detail::compile_parse_context<char>>' requested here
        parse_funcs_{&parse_format_specs<Args, parse_context_type>...},
                      ^
/usr/local/include/fmt/core.h:3159:47: note: in instantiation of member function 'fmt::detail::format_string_checker<char, fmt::detail::error_handler, mppp::integer<1>>::format_string_checker' requested here
      detail::parse_format_string<true>(str_, checker(s, {}));
                                              ^
/usr/ports/math/obake/work/obake-0.8.0/include/obake/polynomials/d_packed_monomial.hpp:436:45: note: in instantiation of function template specialization 'fmt::basic_format_string<char, mppp::integer<1> &>::basic_format_string<char[8], 0>' requested here
                    *cur_oss << fmt::format("^{{{}}}", tmp_mp);
                                            ^
/usr/local/include/fmt/core.h:1124:3: note: 'fallback_formatter' has been explicitly marked deleted here
  fallback_formatter() = delete;
  ^
/usr/local/include/fmt/core.h:1756:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/local/include/fmt/core.h:1777:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, mppp::integer<1> &>' requested here
  return make_value<Context>(val);
         ^
/usr/local/include/fmt/core.h:1899:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, mppp::integer<1> &, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/local/include/fmt/core.h:1918:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, mppp::integer<1>>::format_arg_store<mppp::integer<1> &>' requested here
  return {FMT_FORWARD(args)...};
         ^
/usr/local/include/fmt/core.h:3206:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, mppp::integer<1> &>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                           ^
/usr/ports/math/obake/work/obake-0.8.0/include/obake/polynomials/d_packed_monomial.hpp:436:38: note: in instantiation of function template specialization 'fmt::format<mppp::integer<1> &>' requested here
                    *cur_oss << fmt::format("^{{{}}}", tmp_mp);
                                     ^
2 errors generated.
[ 50% 2/4] /usr/local/libexec/ccache/c++ -DFMT_SHARED -Dobake_EXPORTS -I/usr/ports/math/obake/work/obake-0.8.0/include -I/usr/ports/math/obake/work/.build/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -ftemplate-depth=1024 -fdiagnostics-show-template-tree -pthread -std=c++20 -MD -MT CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o -MF CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o.d -o CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o -c /usr/ports/math/obake/work/obake-0.8.0/src/polynomials/packed_monomial.cpp
FAILED: CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o 
/usr/local/libexec/ccache/c++ -DFMT_SHARED -Dobake_EXPORTS -I/usr/ports/math/obake/work/obake-0.8.0/include -I/usr/ports/math/obake/work/.build/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -ftemplate-depth=1024 -fdiagnostics-show-template-tree -pthread -std=c++20 -MD -MT CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o -MF CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o.d -o CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o -c /usr/ports/math/obake/work/obake-0.8.0/src/polynomials/packed_monomial.cpp
In file included from /usr/ports/math/obake/work/obake-0.8.0/src/polynomials/packed_monomial.cpp:17:
/usr/local/include/fmt/core.h:2743:12: error: call to deleted constructor of 'conditional_t<has_formatter<mapped_type, context>::value, formatter<mapped_type, char_type>, fallback_formatter<stripped_type, char_type>>' (aka 'fmt::detail::fallback_formatter<mppp::integer<1>>')
  auto f = conditional_t<has_formatter<mapped_type, context>::value,
           ^
/usr/local/include/fmt/core.h:2954:23: note: in instantiation of function template specialization 'fmt::detail::parse_format_specs<mppp::integer<1>, fmt::detail::compile_parse_context<char>>' requested here
        parse_funcs_{&parse_format_specs<Args, parse_context_type>...},
                      ^
/usr/local/include/fmt/core.h:3159:47: note: in instantiation of member function 'fmt::detail::format_string_checker<char, fmt::detail::error_handler, mppp::integer<1>>::format_string_checker' requested here
      detail::parse_format_string<true>(str_, checker(s, {}));
                                              ^
/usr/ports/math/obake/work/obake-0.8.0/src/polynomials/packed_monomial.cpp:172:41: note: in instantiation of function template specialization 'fmt::basic_format_string<char, mppp::integer<1> &>::basic_format_string<char[8], 0>' requested here
                *cur_oss << fmt::format("^{{{}}}", tmp_mp);
                                        ^
/usr/local/include/fmt/core.h:1124:3: note: 'fallback_formatter' has been explicitly marked deleted here
  fallback_formatter() = delete;
  ^
/usr/local/include/fmt/core.h:1756:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/local/include/fmt/core.h:1777:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, mppp::integer<1> &>' requested here
  return make_value<Context>(val);
         ^
/usr/local/include/fmt/core.h:1899:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, mppp::integer<1> &, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/local/include/fmt/core.h:1918:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, mppp::integer<1>>::format_arg_store<mppp::integer<1> &>' requested here
  return {FMT_FORWARD(args)...};
         ^
/usr/local/include/fmt/core.h:3206:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, mppp::integer<1> &>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                           ^
/usr/ports/math/obake/work/obake-0.8.0/src/polynomials/packed_monomial.cpp:172:34: note: in instantiation of function template specialization 'fmt::format<mppp::integer<1> &>' requested here
                *cur_oss << fmt::format("^{{{}}}", tmp_mp);
                                 ^
/usr/ports/math/obake/work/obake-0.8.0/src/polynomials/packed_monomial.cpp:204:13: note: in instantiation of function template specialization 'obake::polynomials::detail::(anonymous namespace)::packed_monomial_tex_stream_insert<int>' requested here
    detail::packed_monomial_tex_stream_insert(os, m, s);
            ^
2 errors generated.
```

libfmt-9.1.0
clang-14
FreeBSD 13.1

**Comment by bluescarni** [comment]
@yurivict thanks for the report.

I cannot understand what is going on though, since on ``conda`` obake was built successfully against fmt 9.1.0 on several configurations. E.g., see here for a build log on OSX using clang-14:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=658749&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b

I'll try to set up a local build environment with clang-14 on my machine to see if I can reproduce.

**Comment by yurivict** [comment]
This error maybe specific to the combination of clang and the C++ library that it uses.

The easiest way to reproduce might be to install a FreeBSD VM.

**Comment by bluescarni** [comment]
Ok thanks for the heads up, it may take a couple of days but I should be able to set up a FreeBSD environment on VirtualBox.

**Comment by rfenrich** [comment]
Hello, I confirm I have this same issue. Is there any progress?

**Comment by gl-yziquel** [comment]
I get the same issue if I use clang 14 and fmt 9.1.0, 9.0.0 on ubuntu. Not freebsd but ubuntu.

Same for gcc 11.4.0-1ubuntu~22.04 (well, the errors are different, but it fails to compile).

Fmt above version 10 also does not compile.

Given that this is a "reproducible build" issue, I'd suggest using FetchContent in cmake. Or get Conan into the loop. Short of going for some Bazel or Buck2 solution which I believe will be considered too heavy.

For gcc 11.4, ubuntu 22.04, fmt 9.1.0, one gets the following error:

```console
In file included from /home/mini-me/home/cellar/obake/src/polynomials/packed_monomial.cpp:17:
/usr/local/include/fmt/core.h: In instantiation of ‘constexpr decltype (ctx.begin()) fmt::v9::detail::parse_format_specs(ParseContext&) [with T = mppp::integer<1>; ParseContext = fmt::v9::detail::compile_parse_context<char, fmt::v9::detail::error_handler>; decltype (ctx.begin()) = const char*]’:
/usr/local/include/fmt/core.h:2954:9:   required from ‘constexpr fmt::v9::detail::format_string_checker<Char, ErrorHandler, Args>::format_string_checker(fmt::v9::basic_string_view<Char>, ErrorHandler) [with Char = char; ErrorHandler = fmt::v9::detail::error_handler; Args = {mppp::integer<1>}]’
/home/mini-me/home/cellar/obake/src/polynomials/packed_monomial.cpp:172:40:   required from ‘void obake::polynomials::detail::{anonymous}::packed_monomial_tex_stream_insert(std::ostream&, const obake::polynomials::packed_monomial<T>&, const symbol_set&) [with T = int; std::ostream = std::basic_ostream<char>; obake::symbol_set = boost::container::flat_set<std::__cxx11::basic_string<char> >]’
/home/mini-me/home/cellar/obake/src/polynomials/packed_monomial.cpp:204:46:   required from here
/home/mini-me/home/cellar/obake/src/polynomials/packed_monomial.cpp:172:40:   in ‘constexpr’ expansion of ‘fmt::v9::basic_format_string<char, mppp::integer<1>&>("^{{{}}}")’
/usr/local/include/fmt/core.h:2743:12: error: use of deleted function ‘fmt::v9::detail::fallback_formatter<T, Char, Enable>::fallback_formatter() [with T = mppp::integer<1>; Char = char; Enable = void]’
 2743 |   auto f = conditional_t<has_formatter<mapped_type, context>::value,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2744 |                          formatter<mapped_type, char_type>,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2745 |                          fallback_formatter<stripped_type, char_type>>();
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/fmt/core.h:1124:3: note: declared here
 1124 |   fallback_formatter() = delete;
      |   ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/obake.dir/build.make:230: CMakeFiles/obake.dir/src/polynomials/packed_monomial.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/obake.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by andrewcorrigan** [comment]
I just tried the latest obake+mppp+fmtlib and am seeing the following error using Xcode (Apple clang version 14.0.0 (clang-1400.0.29.202))

```
In file included from /third_party/obake/include/obake/polynomials/d_packed_monomial.hpp:30:
/third_party/fmt/include/fmt/core.h:2582:45: error: implicit instantiation of undefined template 'fmt::detail::type_is_unformattable_for<mppp::integer<1>, char>'
    type_is_unformattable_for<T, char_type> _;
                                            ^
/third_party/fmt/include/fmt/core.h:2645:23: note: in instantiation of function template specialization 'fmt::detail::parse_format_specs<mppp::integer<1>, fmt::detail::compile_parse_context<char>>' requested here
        parse_funcs_{&parse_format_specs<Args, parse_context_type>...} {}
                      ^
/third_party/fmt/include/fmt/core.h:2776:47: note: in instantiation of member function 'fmt::detail::format_string_checker<char, mppp::integer<1>>::format_string_checker' requested here
      detail::parse_format_string<true>(str_, checker(s));
                                              ^
/third_party/obake/include/obake/polynomials/d_packed_monomial.hpp:436:45: note: in instantiation of function template specialization 'fmt::basic_format_string<char, mppp::integer<1> &>::basic_format_string<char[8], 0>' requested here
                    *cur_oss << fmt::format("^{{{}}}", tmp_mp);
```

Different error, but also triggered by the code `fmt::format("^{{{}}}", `

**Comment by andrewcorrigan** [comment]
I just tried updating to latest obake+mppp+fmtlib again and it's all working for me now.

**Comment by gl-yziquel** [comment]
@andrewcorrigan

I tried building all dependencies living on HEAD, and no, it still is not solved for me.

Could you please provide the exact versions of obake, mppp, abseil and fmt that worked for you ? So that I may try replicating the build ?

**Comment by andrewcorrigan** [comment]
It was latest trunk of each repository as of yesterday.   Perhaps the issue I encountered is not the same as yours.

**Comment by bluescarni** [comment]
@andrewcorrigan @gl-yziquel sorry for dropping the ball on this, I completely forgot about this report.

The conda recipe for obake incorporates a fix for this issue:

https://github.com/conda-forge/obake-feedstock/blob/main/recipe/fmt_fix.diff

I will try to include the patch in the next obake version, hopefully next week if I have time. Of course if you want to help, testing the patch and PRs are always welcome :)

**Comment by gl-yziquel** [comment]
I unfortunately struggle to find time for this. Which is a shame as it is a dependency for the genetic algorithm backpropagation library I had my eyes on. Hope I'll find time to come back to it.

**Comment by h-vetinari** [comment]
Unfortunately, the fmt problems keep coming back even with the patch in the conda-forge feedstock: Building obake 0.8.0 (+ the patch) against fmt 11 [fails](https://github.com/conda-forge/obake-feedstock/pull/47) in conda-forge.

**Comment by bluescarni** [comment]
This should now be fixed in master, I will release 0.9 shortly.

@gl-yziquel do you have a link to the genetic backpropagation library?

**Comment by gl-yziquel** [comment]
@bluescarni 

I just did a git pull and attempted to build it on bb8f73206c23cf520729fd131a7254444ff97245. I still get a failure related to `formattable`.

As to the genetic backpropagation library, I kind of do not have the picture of what it is precisely after all these months, but it is likely what I'd like to toy with. (I do remember reading cursorily the "Differentiable genetic programming" paper, though, which is what I'm interested in).

**Comment by bluescarni** [comment]
Do you have the latest version of all dependencies? The CI is green on master:

https://app.circleci.com/pipelines/github/bluescarni/obake/1443/workflows/df6658cd-9718-4a9c-b30a-0664dd737e24/jobs/5186/parallel-runs/0/steps/0-102

These are the versions in the conda environment, for reference:

```
  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  arb                conda-forge/linux-64::arb-2.23.0-h44d021b_0 
  backtrace          conda-forge/linux-64::backtrace-20220708-h753d276_0 
  binutils           conda-forge/linux-64::binutils-2.43-h4852527_1 
  binutils_impl_lin~ conda-forge/linux-64::binutils_impl_linux-64-2.43-h4bf12b8_1 
  binutils_linux-64  conda-forge/linux-64::binutils_linux-64-2.43-h4852527_1 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_7 
  c-ares             conda-forge/linux-64::c-ares-1.34.1-heb4867d_0 
  c-compiler         conda-forge/linux-64::c-compiler-1.8.0-h2b85faf_0 
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.8.30-hbcca054_0 
  cmake              conda-forge/linux-64::cmake-3.30.5-hf9cb763_0 
  cxx-compiler       conda-forge/linux-64::cxx-compiler-1.8.0-h1a2810e_0 
  fmt                conda-forge/linux-64::fmt-11.0.2-h434a139_0 
  gcc                conda-forge/linux-64::gcc-13.3.0-h9576a4e_1 
  gcc_impl_linux-64  conda-forge/linux-64::gcc_impl_linux-64-13.3.0-hfea6d02_1 
  gcc_linux-64       conda-forge/linux-64::gcc_linux-64-13.3.0-hc28eda2_4 
  gf2x               conda-forge/linux-64::gf2x-1.3.0-ha476b99_2 
  gmp                conda-forge/linux-64::gmp-6.3.0-hac33072_2 
  gxx                conda-forge/linux-64::gxx-13.3.0-h9576a4e_1 
  gxx_impl_linux-64  conda-forge/linux-64::gxx_impl_linux-64-13.3.0-hdbfa832_1 
  gxx_linux-64       conda-forge/linux-64::gxx_linux-64-13.3.0-h6834431_4 
  icu                conda-forge/linux-64::icu-75.1-he02047a_0 
  kernel-headers_li~ conda-forge/noarch::kernel-headers_linux-64-3.10.0-he073ed8_17 
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 
  krb5               conda-forge/linux-64::krb5-1.21.3-h659f571_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.43-h712a8e2_1 
  libboost           conda-forge/linux-64::libboost-1.86.0-hb8260a3_2 
  libboost-devel     conda-forge/linux-64::libboost-devel-1.86.0-h1a2810e_2 
  libboost-headers   conda-forge/linux-64::libboost-headers-1.86.0-ha770c72_2 
  libcurl            conda-forge/linux-64::libcurl-8.10.1-hbbe4b11_0 
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 
  libev              conda-forge/linux-64::libev-4.33-hd590300_2 
  libexpat           conda-forge/linux-64::libexpat-2.6.3-h5888daf_0 
  libflint           conda-forge/linux-64::libflint-2.9.0-h2f819a4_ntl_100 
  libgcc             conda-forge/linux-64::libgcc-14.1.0-h77fa898_1 
  libgcc-devel_linu~ conda-forge/noarch::libgcc-devel_linux-64-13.3.0-h84ea5a7_101 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-14.1.0-h69a702a_1 
  libgomp            conda-forge/linux-64::libgomp-14.1.0-h77fa898_1 
  libhwloc           conda-forge/linux-64::libhwloc-2.11.1-default_hecaa2ac_1000 
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1 
  libsanitizer       conda-forge/linux-64::libsanitizer-13.3.0-heb74ff8_1 
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 
  libstdcxx          conda-forge/linux-64::libstdcxx-14.1.0-hc0a3c3a_1 
  libstdcxx-devel_l~ conda-forge/noarch::libstdcxx-devel_linux-64-13.3.0-h84ea5a7_101 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-14.1.0-h4852527_1 
  libuv              conda-forge/linux-64::libuv-1.49.1-hb9d3cd8_0 
  libxml2            conda-forge/linux-64::libxml2-2.12.7-he7c6b58_4 
  libzlib            conda-forge/linux-64::libzlib-1.3.1-hb9d3cd8_2 
  mpc                conda-forge/linux-64::mpc-1.3.1-h24ddda3_1 
  mpfr               conda-forge/linux-64::mpfr-4.2.1-h90cbb55_3 
  mppp               conda-forge/linux-64::mppp-1.0.4-h828bdaa_0 
  ncurses            conda-forge/linux-64::ncurses-6.5-he02047a_1 
  ninja              conda-forge/linux-64::ninja-1.12.1-h297d8ca_0 
  ntl                conda-forge/linux-64::ntl-11.4.3-hef3c4d3_1 
  openssl            conda-forge/linux-64::openssl-3.3.2-hb9d3cd8_0 
  rhash              conda-forge/linux-64::rhash-1.4.4-hd590300_0 
  sysroot_linux-64   conda-forge/noarch::sysroot_linux-64-2.17-h4a8ded7_17 
  tbb                conda-forge/linux-64::tbb-2021.13.0-h84d6215_0 
  tbb-devel          conda-forge/linux-64::tbb-devel-2021.13.0-h94b29a5_0 
  tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0 
  ```

**Comment by gl-yziquel** [comment]
> Do you have the latest version of all dependencies? The CI is green on master:

Likely not. My custom build infrastructure does not yet manage that well enough.

I'll have a look. It might take me quite a lot of time to get around it, however.
